CREATE TABLE "ContentRecord" (
	"accountDirection" text,
	"accountName" text,
	"accountType" text,
	"aiMaterials" text,
	"attachment" text,
	"copyText" text,
	"copyWriter" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"language" text,
	"notes" text,
	"photographer" text,
	"plannedAt" timestamp,
	"platform" text,
	"product" text,
	"rawData" jsonb NOT NULL,
	"recordType" varchar(32) NOT NULL,
	"referenceVideo" text,
	"reviewStatus" text,
	"revisedCopy" text,
	"scriptDocument" text,
	"searchText" text NOT NULL,
	"shootConfirmed" text,
	"shootingScene" text,
	"sourceRow" integer NOT NULL,
	"sourceSheet" varchar(64) NOT NULL,
	"submitter" text,
	"tags" text,
	"targetTopic" text,
	"title" text,
	"usageStatus" text,
	"videoType" text
);
--> statement-breakpoint
CREATE UNIQUE INDEX "ContentRecord_sourceSheet_sourceRow_idx" ON "ContentRecord" USING btree ("sourceSheet","sourceRow");